### ISSUE TITLE
DB1 Issue

### ISSUE THREAD

**Issue by jamesrf** [pitthsls/pycounter#59]
Hi!  I am having trouble parsing DB1 data downloaded via SUSHI from EBSCO and ProQuest:

```
>>> import pycounter.report
>>> r = pycounter.report.parse("proquest-DB1.tsv")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pycounter/report.py", line 526, in parse
    return parse_separated(filename, '\t', encoding, fallback_encoding)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pycounter/report.py", line 575, in parse_separated
    return parse_generic(report_reader)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pycounter/report.py", line 616, in parse_generic
    report.year = _year_from_header(header, report)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pycounter/report.py", line 769, in _year_from_header
    year = int(header[first_date_col].split('-')[1])
IndexError: list index out of range
```

I think this block is the problem:
```
    elif report.report_type == 'DB1' and report.report_version == 4:
        first_date_col = 6
    elif report.report_type == 'DB2' and report.report_version == 4:
        first_date_col = 5
    year = int(header[first_date_col].split('-')[1])
```

My actual DB1 report (first few lines, account # redacted) looks like this:
```
Database Report 1 (R4)  Total Searches, Result Clicks and Record Views by Month and Database
Account #REDACTED# - #REDACTED#
#REDACTED#
Period covered by Report:
2016-01-01 to 2016-01-31
Date run:
2018-05-07
Database        Publisher       Platform        User Activity   Reporting Period Total  Jan-2016
CBCA Reference & Current Events ProQuest        ProQuest        Regular Searches        251     251
CBCA Reference & Current Events ProQuest        ProQuest        Searches-federated and automated        0       0
CBCA Reference & Current Events ProQuest        ProQuest        Result Clicks   31      31
```

It looks like the `first_date_col` for DB1 report is should be 5 and not 6

**Comment by jamesrf** [comment]
Just to add additional insight: most users probably do multi-month reports.  In this more normal use case, column 6 would be Feb-2016, and there would be no error, the code would extract year from that.    In my case, I am only doing a single month report

**Comment by jamesrf** [comment]
See PR #60
