### ISSUE TITLE
AttributeError when downloading JR1 or DB1 from Gale

### ISSUE THREAD

**Issue by MarkEEaton** [pitthsls/pycounter#72]
Hi,

Pycounter throws the error below when trying to download a report from Gale. I've only been able to generate this error with Gale, and our credentials for Gale's SUSHI service seem to be authenticating properly. Let me how I can help...

```
Traceback (most recent call last):
  File "app.py", line 29, in <module>
    main()
  File "app.py", line 21, in main
    sushi_dump=True)
  File "C:\Users\MEaton\git\pycounter\venv3.6\lib\site-packages\pycounter\sushi.py", line 123, in get_report
    return _raw_to_full(raw_report)
  File "C:\Users\MEaton\git\pycounter\venv3.6\lib\site-packages\pycounter\sushi.py", line 190, in _raw_to_full
    inst_id = customer.find('.//%s' % _ns('counter', 'ID')).text
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by Wooble** [comment]
It sounds like you're getting back a response without the customer information that's supposed to be part of it. I think this is strictly speaking a bug on their end, but pycounter should definitely handle it more elegantly.

**Comment by Wooble** [comment]
Mark,

Can you check that there's actual usage data in the XML you're dumping? This specific exception should be caught now, but looking deeper it seems like the actual report should be under the same element that's being shown as a "'NoneType' object" here so there may be more to do.

I don't have any Gale titles, so a copy of the dump might also be helpful to debug.

**Comment by MarkEEaton** [comment]
Yes, I will take a look this afternoon...

**Comment by MarkEEaton** [comment]
Here's the the dump as it appears in the log: 
https://gist.github.com/MarkEEaton/6b0bd90aedab487ac0ff669a5ed1b496

You're right that there's no actual Counter data there.

**Comment by MarkEEaton** [comment]
Once I showed Gale the problematic dumped XML, they were able to resolve this by issuing me new credentials.
